FROM ubuntu:latest

# set working directory in the image

WORKDIR /app

# copy files from host file system to the image file system

COPY . /app

# Install necessary packages
RUN apt-get update && apt-get install -y python3 python3-pip

# Set env variable
ENV NAME World

# Run the command to start the application
CMD ["python3", "app.py"]

